project:
  type: website

website:
  title: "mw-playground"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - game.qmd
      - about.qmd
    right:
      - icon: github
        href: "https://github.com/manwho007/mw-playgruond"
        aria-label: R Playground
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
